### ISSUE TITLE
Include LICENSE.txt in the nupkg

### ISSUE THREAD

**Issue by MarkSchofield** [craigktreasure/Treasure.Utils#52]
In order to be compliant with the LICENSE.txt, I'm supposed to include the copyright notice in all copies of the software. So if I depend on the NuGet, and want to make my own NuGet, then I need to include the copyright notice. And that would be drastically easier if the LICENSE.txt was in the Treasure.Utils.Arguments nupkg.

**Comment by craigktreasure** [comment]
I think that's fine, but I'd also like to understand your requirements. Your PR includes the license file. There's also a field for a license url I believe.

**Comment by MarkSchofield** [comment]
The LICENSE.txt says - amongst other things:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

If I 'dotnet publish' my project, then your assembly gets dropped alongside. That feels like a 'substantial portion of the Software', so I need to include the copyright notice and permission notice, right? It being MIT licensed is one thing, but I also need to comply with LICENSE.txt, don't I?

**Comment by MarkSchofield** [comment]
If I'm doing something wrong, let me know... I'm surprised there's not more [msbuild] infrastructure for pulling together dependent `LICENSE`'s into a `ThirdPartyNotices`.

**Comment by craigktreasure** [comment]
Thanks for calling this out. I hadn't previously noticed that the MIT license required a copy of the license to be distributed. I thought it was simpler than that.

Ok. [This](https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices) suggests that we should not use `licenseUrl`. Good to know.

This is confusing. I'm not sure I get the point of the license expression if you still have to include the license file and the expression is going to result in a link on nuget.org to a different license file. Apparently, it isn't sufficient to specify the expression to comply with the license? Or is the expression sufficient, assuming you get the license from the link on nuget.org, but that isn't convenient for some tooling? Or is it more complicated because I also have a license file in my repo (which I feel is the responsible thing to do)?

If we replaced `PackageLicenseExpression` at https://github.com/craigktreasure/Treasure.Utils/blob/0c60411a13e11682d88eec1d645e0a7d24bb9b21/eng/Packaging.props#L13C5-L13C61 with `<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>`, we should get the license file hooked up correctly. The downside is that it wouldn't be quickly visible from NuGet.org that it's licensed using MIT.

**Comment by MarkSchofield** [comment]
Well, I think the license expression is a great way to say that it's MIT licensed. Which it is. If you navigate to this link <https://github.com/craigktreasure/Treasure.Utils/blob/main/LICENSE.txt> GitHub puts a summary on-top that shows the Permissions, Limitations and Conditions - and without the LICENSE file in the nupkg, it's hard for consumers to comply with the Conditions.

**Comment by MarkSchofield** [comment]
> Ok. [This](https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices) suggests that we should not use licenseUrl. Good to know.

Well, hold on there. `licenseUrl` is different from `PackageLicenseExpression`. You're using `PackageLicenseExpression` which is right. The weird part is that the build disallows `PackageLicenseExpression` and `PackageLicenseFile`, when `PackageLicenseFile` seems like a great way to comply with the license's Conditions.
